Add support for tileserver APIs taking latitude and longitude values instead of tile coordinates
nobleo/rviz_satellite pull request #107
Opened 2022-10-17 15:36 UTC by ndunkelivi

Tile Servers like Googles Static Map API require a pair of latitude and longitude values instead of x-y tile coordinates. Therefore, it is now supported to use {lat} and {lon} as placeholders in the tileserver URL. These will be automatically replaced by rviz_satellite according to the center coordinate of each tile when making HTTP requests.

2022-11-18 16:34 UTC, peci1 commented on src/tile_id.cpp
> +  boost::replace_all(url, "{lon}", std::to_string(lon_deg));
There already is a dedicated function to convert tile ID to WGS coords.

Also, std::to_string fails on machines with a locale that renders floats with a decimal comma, e.g. German or Czech. To get locale-independent stringified version of the float, you have to use either boost::lexical_cast, or std::to_chars (available only in C++17 and newer).

```suggestion
  // compute latitude and longitude from tile coordinates
  const auto wgs = toWGSCoordinate(tile_id.coord, tile_id.zoom);

  // substitute placeholders
  boost::replace_all(url, "{lat}", boost::lexical_cast<std::string>(wgs.lat));
  boost::replace_all(url, "{lon}", boost::lexical_cast<std::string>(wgs.lon));
```

2022-11-18 16:37 UTC, peci1 commented on src/tile_id.cpp
```suggestion
#include <boost/lexical_cast.hpp>

```

2022-11-18 23:11 UTC, peci1 commented
Please, also update the regex and error message at https://github.com/nobleo/rviz_satellite/blob/78227f6f4e5d8fd913a00c65858b5f4ec0c9a5a0/src/aerialmap_display.cpp#L291-L293 .

The correct regex is `R"(.*\{([xyz]|lat|lon)\}.*)"`.

2022-11-18 23:12 UTC, peci1 commented
I've tested this PR and it works (given you apply all the code suggestions).

2022-11-18 23:13 UTC, peci1 requested changes
I've tested this PR and it works (given you apply the proposed code changes).

2022-11-21 09:56 UTC, ndunkelivi commented
Thank you for the review and improvements. I applied and tested your suggested code changes and it works as well.

2022-11-21 09:59 UTC, peci1 approved these changes
Thanks!

2023-02-21 13:29 UTC, merged